################ English language ##################
[fr]
languageCode = "fr-FR"
languageName = "Français"
contentDir = "content/french"
weight = 1

[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

